name: Build Docker image (PR)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
